/// Centralized localization dictionary for the Smart Soil application.
/// Strictly preserves app branding 'Smart Soil' / 'स्मार्ट सॉइल' with bilingual English & Hindi support.
class AppStrings {
  const AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Smart Soil',
      'tagline': 'AI-Powered Precision Agriculture & Soil Health',
      'language_select': 'Select Language',
      'greeting_prefix': 'Hello,',
      'welcome_subtitle': 'Welcome to Smart Soil',
      'scan_your_crop': 'Scan Your Crop',
      'scan_subtitle': 'Detect diseases and get instant solutions',
      'open_camera': 'Open Camera',
      'live_weather': 'Live Weather & Risk',
      'feels_like': 'Feels like',
      'humidity': 'Humidity',
      'rainfall': 'Rainfall',
      'wind': 'Wind',
      'agri_risk': 'Agri Risk',
      'high_risk': 'High Risk',
      'moderate_risk': 'Moderate Risk',
      'low_risk': 'Low Risk',
      'risk_advisory': 'Advisory: High humidity & favorable temperatures create elevated risk of fungal blight.',
      'soil_health_index': 'Soil Health Index',
      'soil_moisture': 'Soil Moisture',
      'soil_ph': 'Soil pH',
      'nitrogen': 'Nitrogen (N)',
      'phosphorus': 'Phosphorus (P)',
      'potassium': 'Potassium (K)',
      'climate': 'Soil Temp & Humidity',
      'farmers_news': 'Farmers News',
      'news_1_title': 'Kharif Water Management: Can Farmers Save More Water?',
      'news_1_date': '2 days ago • Water Conservation',
      'news_2_title': 'Laser Weeding Machines: The Future of Weed Control',
      'news_2_date': '4 days ago • Tech Insights',
      'tab_home': 'Home',
      'tab_scan': 'Scan',
      'tab_yield': 'Yield',
      'tab_ai': 'Ask AI',
      'tab_farm': 'Soil & Farm',
      'scan_title': 'AI Crop Disease Scanner',
      'scan_instructions': 'Align crop leaf inside the viewfinder box',
      'select_sample_leaf': 'Or test with sample leaf:',
      'sample_early_blight': 'Tomato Early Blight',
      'sample_healthy': 'Healthy Wheat',
      'sample_late_blight': 'Potato Late Blight',
      'sample_curl': 'Cotton Leaf Curl',
      'diagnosis_result': 'AI Diagnosis Result',
      'confidence': 'AI Confidence',
      'severity': 'Severity',
      'symptoms': 'Symptoms',
      'recommended_treatment': 'Recommended Treatment',
      'yield_title': 'AI Crop Yield Prediction',
      'yield_subtitle': 'Multi-factor prediction using real-time NPK & moisture telemetry',
      'select_crop': 'Select Target Crop',
      'farm_size': 'Farm Size (Acres)',
      'predicted_yield': 'Predicted Yield',
      'per_acre': 'Quintals / Acre',
      'total_harvest': 'Total Estimated Harvest',
      'optimization_tip': 'Optimization Advisory',
      'chat_title': 'Smart Soil Agronomic AI',
      'chat_welcome': 'Hello! I am your Smart Soil AI Assistant. Ask me anything about crop diseases, soil fertility, or fertilizer schedules.',
      'chat_placeholder': 'Ask in English or हिन्दी...',
      'chip_fungal': 'Treat fungal blight?',
      'chip_npk': 'Best fertilizer for current soil pH?',
      'chip_moisture': 'Is moisture optimal for sowing?',
      'telemetry_title': 'Hardware Telemetry & Node Status',
      'device_status': 'ESP32 IoT Sensor Node',
      'status_online': 'Online • Low Latency',
      'scenario_optimal': 'Optimal Soil',
      'scenario_drought': 'Drought Alert',
      'scenario_waterlogged': 'Waterlogged Soil',
    },
    'hi': {
      'app_title': 'स्मार्ट सॉइल',
      'tagline': 'एआई-संचालित सटीक कृषि और मृदा स्वास्थ्य प्रबंधन',
      'language_select': 'भाषा चुनें',
      'greeting_prefix': 'नमस्ते,',
      'welcome_subtitle': 'स्मार्ट सॉइल में आपका स्वागत है',
      'scan_your_crop': 'अपनी फसल स्कैन करें',
      'scan_subtitle': 'रोगों का तुरंत पता लगाएं और सटीक समाधान पाएं',
      'open_camera': 'कैमरा खोलें',
      'live_weather': 'मौसम और कृषि जोखिम',
      'feels_like': 'महसूस',
      'humidity': 'नमी',
      'rainfall': 'बारिश',
      'wind': 'हवा की गति',
      'agri_risk': 'कृषि जोखिम',
      'high_risk': 'उच्च जोखिम',
      'moderate_risk': 'मध्यम जोखिम',
      'low_risk': 'कम जोखिम',
      'risk_advisory': 'सलाह: उच्च आर्द्रता और अनुकूल तापमान के कारण फफूंद (Fungus/Blight) का खतरा अधिक है।',
      'soil_health_index': 'मृदा स्वास्थ्य सूचकांक',
      'soil_moisture': 'मिट्टी की नमी',
      'soil_ph': 'मृदा पीएच (pH)',
      'nitrogen': 'नाइट्रोजन (N)',
      'phosphorus': 'फास्फोरस (P)',
      'potassium': 'पोटेशियम (K)',
      'climate': 'मृदा तापमान और आर्द्रता',
      'farmers_news': 'किसान समाचार',
      'news_1_title': 'खरीफ जल प्रबंधन: क्या किसान अधिक पानी बचा सकते हैं?',
      'news_1_date': '2 दिन पहले • जल संरक्षण',
      'news_2_title': 'लेजर वीडिंग मशीनें: खरपतवार नियंत्रण का आधुनिक भविष्य',
      'news_2_date': '4 दिन पहले • कृषि तकनीक',
      'tab_home': 'होम',
      'tab_scan': 'स्कैन',
      'tab_yield': 'उपज',
      'tab_ai': 'एआई',
      'tab_farm': 'मिट्टी/खेत',
      'scan_title': 'एआई फसल रोग स्कैनर',
      'scan_instructions': 'पत्ती को स्कैनर फ्रेम के बीच में रखें',
      'select_sample_leaf': 'या नमूना पत्ती से परीक्षण करें:',
      'sample_early_blight': 'टमाटर अगेती झुलसा',
      'sample_healthy': 'स्वस्थ गेहूं',
      'sample_late_blight': 'आलू पछेती झुलसा',
      'sample_curl': 'कपास पत्ती मरोड़',
      'diagnosis_result': 'एआई जांच परिणाम',
      'confidence': 'एआई सटीकता',
      'severity': 'गंभीरता',
      'symptoms': 'लक्षण',
      'recommended_treatment': 'अनुशंसित उपचार और दवा',
      'yield_title': 'एआई फसल उपज पूर्वानुमान',
      'yield_subtitle': 'मिट्टी के एनपीके और नमी आंकड़ों पर आधारित उत्पादन गणना',
      'select_crop': 'फसल का चयन करें',
      'farm_size': 'खेत का आकार (एकड़)',
      'predicted_yield': 'अनुमानित पैदावार',
      'per_acre': 'क्विंटल / एकड़',
      'total_harvest': 'कुल अनुमानित उत्पादन',
      'optimization_tip': 'पैदावार सुधार सुझाव',
      'chat_title': 'स्मार्ट सॉइल एआई सहायक',
      'chat_welcome': 'नमस्ते! मैं आपका स्मार्ट सॉइल एआई सहायक हूँ। मुझसे फसल रोग, मिट्टी की उर्वरता या खाद के बारे में कुछ भी पूछें।',
      'chat_placeholder': 'हिंदी या अंग्रेजी में पूछें...',
      'chip_fungal': 'फफूंद रोग का उपचार?',
      'chip_npk': 'मौजूदा पीएच के लिए सबसे अच्छी खाद?',
      'chip_moisture': 'क्या बुवाई के लिए नमी अनुकूल है?',
      'telemetry_title': 'हार्डवेयर सेंसर और नोड स्थिति',
      'device_status': 'ईएसपी32 आईओटी सेंसर नोड',
      'status_online': 'सक्रिय • निर्बाध संपर्क',
      'scenario_optimal': 'अनुकूल मिट्टी',
      'scenario_drought': 'सूखा चेतावनी',
      'scenario_waterlogged': 'जलभराव चेतावनी',
    },
  };

  static String get(String key, {String locale = 'en'}) {
    final langMap = _localizedValues[locale] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}
